SUBDIRS += android/objs/emulator_common
#SUBDIRS += android/objs/emulator_libqemu
SUBDIRS += android/objs/emulator_libui
SUBDIRS += android/objs/android
#SUBDIRS += android/objs/android_common
#SUBDIRS += android/objs/setup

bin_PROGRAMS = emulator
emulator_SOURCES = utils/main/android_emulator.c
emulator_SOURCES += android/utils/setenv.c

emulator_LDADD =  -L./common -lcommon

