/* Copyright (C)
* xq2537@gmail.com
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
* 
*/
/**
* @file lcd_sdl.h
* @brief The definition of system controller 
* @author xq2537@gmail.com
* @version 78.77
*/

/* Autogenerated by SkyEye script */
#ifndef __lcd_sdl_H__
#define __lcd_sdl_H__

#include <skyeye_types.h>
#include <skyeye_lcd_intf.h>
#include <skyeye_obj.h>
#include <skyeye_signal.h>
#include <memory_space.h>
#include "android/skyeye/console.h"

typedef struct fb_state {
	DisplayState*  ds;
	int      pixel_format;
	int      bytes_per_pixel;
	uint32_t fb_base;
	uint32_t base_valid : 1;
	uint32_t need_update : 1;
	uint32_t need_int : 1;
	uint32_t set_rotation : 2;
	uint32_t blank : 1;
	uint32_t int_status;
	uint32_t int_enable;
	int      rotation;   /* 0, 1, 2 or 3 */
	int      dpi;

}fb_state_t;

typedef struct lcd_sdl_device{
	conf_object_t* obj;
	fb_state_t* fb;
	simple_signal_intf* master;
	int width;
	int height;
	int depth;

	uint32 lcd_addr_begin;
	uint32 lcd_addr_end;
	uint32 lcd_line_offset; /* pixels from the line's ending to the next line's starting. */

}lcd_sdl_device;

#endif
